export const samplePhotos = [
  {
    photoId: "street-001",
    imageUrl: "https://picsum.photos/id/1011/1800/2400",
    title: "Crosswalk Silence",
    caption: "Rain gloss on asphalt while the city slows for one red light.",
    poem: "A pause between footsteps, / neon breathing in puddles.",
    collection: "City Life",
    alt: "People crossing a wet street in evening light",
    featured: true,
  },
  {
    photoId: "street-002",
    imageUrl: "https://picsum.photos/id/1005/1600/2000",
    title: "Window Seat",
    caption: "Last train north, faces reflected in scratched glass.",
    poem: "Steel hum, tired eyes, / stations passing like thoughts.",
    collection: "Subway Stories",
    alt: "Portrait through a subway window",
  },
  {
    photoId: "street-003",
    imageUrl: "https://picsum.photos/id/1062/1800/2200",
    title: "Fourth Avenue",
    caption: "A vendor turns pages while afternoon traffic blurs behind him.",
    poem: "Paper dust and engines, / one page held still.",
    collection: "Street Portraits",
    alt: "Street vendor portrait with moving traffic in background",
  },
  {
    photoId: "street-004",
    imageUrl: "https://picsum.photos/id/1035/1700/2200",
    title: "Tunnel Glow",
    caption: "Headlights carve the underpass and disappear into steam.",
    poem: "Night opens briefly, / then folds back to black.",
    collection: "Night Walks",
    alt: "Cars passing through a lit urban underpass",
  },
  {
    photoId: "street-005",
    imageUrl: "https://picsum.photos/id/1044/1700/2400",
    title: "Subway Platform",
    caption: "A quiet minute before the crowd returns with the next train.",
    poem: "Fluorescent winter, / footsteps waiting to begin.",
    collection: "Subway Stories",
    alt: "Empty subway platform with overhead lights",
  },
  {
    photoId: "street-006",
    imageUrl: "https://picsum.photos/id/1050/1800/2200",
    title: "Corner Talk",
    caption: "Two old friends catching up between storefront shutters.",
    poem: "Hands tell the story / before words do.",
    collection: "Street Portraits",
    alt: "Two people talking on a city corner",
  },
  {
    photoId: "street-007",
    imageUrl: "https://picsum.photos/id/1057/1700/2100",
    title: "After Midnight",
    caption: "A lone cyclist cutting through the orange haze.",
    poem: "Chain clicks, / and the avenue exhales.",
    collection: "Night Walks",
    alt: "Cyclist riding through a dim city street at night",
  },
  {
    photoId: "street-008",
    imageUrl: "https://picsum.photos/id/1060/1800/2300",
    title: "Chinatown Noon",
    caption: "Lantern shadows fall over market crates and quick exchanges.",
    poem: "Voices rise and fold, / tomatoes, tea, and light.",
    collection: "City Life",
    alt: "Busy street market scene with hanging lanterns",
  },
  {
    photoId: "street-009",
    imageUrl: "https://picsum.photos/id/1074/1700/2200",
    title: "Signal Wait",
    caption: "Three strangers stand under one sign, each alone.",
    poem: "Green will come, / but not yet.",
    collection: "City Life",
    alt: "Pedestrians waiting under a traffic signal",
  },
];
